#!/usr/bin/env bash

# Source: https://github.com/kubernetes-sigs/kustomize/issues/4120#issuecomment-907882084

set -e

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
YQ="$SCRIPTPATH/../../../yq"
if [[ ! -x "$YQ"  ]]; then
   YQ="$(command -v yq)"
fi

res="$(cat $1)"
sedMap=()

length=$(echo "$res" | $YQ e '.vars | length' -)

for (( i=0; i<$length; i++ ))
do
   var="$(echo "$res" | $YQ e '.vars['$i']' -)"
   varName=$(echo "$var" | $YQ e '.name' -)
   if [ "$(echo "$var" | $YQ e '. | has("env")' -)" == 'true' ]
   then
      envVar=$(echo "$var" | $YQ e '.env' -)
      var="$(echo "$var" | $YQ e '.value = env('$envVar')' -)"
   fi
   varValue="$(echo "$var" | $YQ e '.value' -)"
   sedMap+=(-e "s#\$(${varName})#${varValue}#g")
done

# echo "${sedMap[@]}"
sed "${sedMap[@]}"
