#!/usr/bin/env bash

# Source: https://github.com/kubernetes-sigs/kustomize/issues/4120#issuecomment-907882084

set -e

# YQ binary can be provided in $KUSTOMIZE_PLUGIN_HOME
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
YQ="$SCRIPTPATH/../../../yq"
if [[ ! -x "$YQ"  ]]; then
   set +e
   YQ="$(command -v yq)"
   if [[ ! $? -eq 0 ]]; then
      echo '[ERROR] Need to install 'yq' package (https://github.com/mikefarah/yq).' > /dev/stderr
      exit 1
   fi
fi
set -e

res="$(cat $1)"
sedMap=()

length=$(echo "$res" | $YQ e '.vars | length' -)

for (( i=0; i<$length; i++ ))
do
   var="$(echo "$res" | $YQ e '.vars['$i']' -)"
   varName=$(echo "$var" | $YQ e '.name' -)
   if [ "$(echo "$var" | $YQ e '. | has("env")' -)" == 'true' ]
   then
      envVar=$(echo "$var" | $YQ e '.env' -)
      var="$(echo "$var" | $YQ e '.value = env('$envVar')' -)"
   fi
   varValue="$(echo "$var" | $YQ e '.value' -)"
   sedMap+=(-e "s#\$(${varName})#${varValue}#g")
done

# echo "${sedMap[@]}"
sed "${sedMap[@]}"
